# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  microservice-app:
    image: microservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://microservice-postgresql:5432/microservice
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://microservice-postgresql:5432/microservice
      - JHIPSTER_CACHE_REDIS_SERVER=redis://microservice-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://microservice-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  microservice-postgresql:
    image: postgres:13.2
    # volumes:
    #   - ~/volumes/jhipster/microservice/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=microservice
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
  microservice-redis:
    image: redis:6.2.1
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:6379:6379
